# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 05b243719c155b33ead0c2b1bc7e8af1b64dce9d322f7c95db682c140f51fb3fec8b52817d575caaaa86ad8ae56bca06ed79a951b0851b3d13908d70783d7ad7
  
test:
  secret_key_base: 1320823e64726f11c99ae32284207218348341dfb6346c92baf3d2b0eb95ac2c90cb4df5d5c3e9705629cb4606f09084aae5e652845b0a5abafb5818e666aa43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
